// src/components/widgets/UnknownWidget.vue
<script setup lang="ts">
import type { UnknownWidgetProps } from "~/bindings/widget/unknown/UnknownWidgetProps";

const props = defineProps<UnknownWidgetProps>();
</script>

<template>
  <span
    :class="['widget', 'error']"
    :title="`${$props.kind} is not a valid widget.`"
    >{{ props.kind }}</span
  >
</template>

// src/app/components/widgets/unknown-widget/unknown-widget.component.ts
import { Component, Inject, ViewEncapsulation } from "@angular/core";
import { WIDGET_PROPS } from "..";
import { UnknownWidgetProps } from "../../../../bindings/widget/unknown/UnknownWidgetProps";

@Component({
  selector: "unknown-widget",
  templateUrl: "./unknown-widget.component.html",
  encapsulation: ViewEncapsulation.None,
})
export class UnknownWidgetComponent {
  public constructor(@Inject(WIDGET_PROPS) public props: UnknownWidgetProps) {}

  public get widgetLabel(): string {
    return `${this.props.kind} is not a valid widget.`;
  }
}

<span class="widget error" [title]="widgetLabel" id="UnknownWidget">{{
  props.kind
}}</span>
