// src/app/components/widgets/custom-widget/custom-widget.component.ts
import { Component, Inject, ViewEncapsulation } from "@angular/core";
import { WIDGET_PROPS } from "..";
import { CustomWidgetProps } from "../../../../bindings/widget/custom/CustomWidgetProps";

@Component({
  selector: "custom-widget",
  templateUrl: "./custom-widget.component.html",
  encapsulation: ViewEncapsulation.None,
})
export class CustomWidgetComponent {
  public activeLabelFormatted = "todo";
  public constructor(@Inject(WIDGET_PROPS) public props?: CustomWidgetProps) {}
}

/**

<!-- eslint-disable @typescript-eslint/no-non-null-assertion -->
<script setup lang="ts">
import type { CallbackTypeExecOptions } from "~/bindings/widget/base/CallbackTypeExecOptions";
import type { CustomCommandResponse } from "~/bindings/widget/custom/CustomCommandResponse";
import type { CustomWidgetProps } from "~/bindings/widget/custom/CustomWidgetProps";
import { invoke } from "@tauri-apps/api/tauri";
import { ref, onMounted } from "vue";
import { tryFormatArgsEval, tryFormatEval } from "../../utils/format";
import WidgetWrapper from "../WidgetWrapper.vue";
import Log from "~/utils/log";

const props = defineProps<CustomWidgetProps>();
const defaultLabel = "CustomWidget";
const activeLabelTooltip = ref<string | null>(null);
const activeLabelError = ref<string | null>(null);
const activeLabelFormatted = ref<string>(
  props.label_alt ?? props.label ?? defaultLabel
);

// eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars
let commandResultData: any;
let showAltLabel = false;
const unformattedActiveTooltip = props.label_tooltip ?? "";
let unformattedActiveLabel = props.label ?? defaultLabel;
let commandResult: CustomCommandResponse;

onMounted(async () => {
  if (props.command) {
    await executeCustomCommand();

    if (props.command.interval ?? 0 > 0) {
      setInterval(executeCustomCommand, props.command.interval ?? 1000);
    }
  }
});

const executeCustomCommand = async () => {
  commandResult = await invoke("process_custom_command", {
    command: props.command?.cmd,
    args: props.command?.args ?? [],
    timeout: Math.floor((props.command?.interval ?? 1000) / 2),
  });

  updateActiveLabel();
};

const updateActiveLabel = () => {
  if (commandResult.stdout) {
    try {
      commandResultData = JSON.parse(commandResult.stdout);
    } catch {
      commandResultData = commandResult.stdout.replace("\n", "\\n");
    }
    try {
      activeLabelTooltip.value = props.label_tooltip
        ? tryFormatEval(unformattedActiveTooltip, commandResultData)
        : null;
      activeLabelFormatted.value = tryFormatEval(
        unformattedActiveLabel,
        commandResultData
      );
      activeLabelError.value = null;
    } catch (error) {
      activeLabelTooltip.value = unformattedActiveTooltip;
      activeLabelFormatted.value = unformattedActiveLabel;
      activeLabelError.value = `Error formatting label:\n\n${
        (error as Error).message
      }`;
    }
  } else {
    // If no stdout, format error tooltip
    const cmd = props.command?.cmd;
    const args = ` ${(props.command?.args ?? []).join(" ")}`;
    const status = commandResult.status ?? 1;

    activeLabelError.value = `exited with code: ${status}\n\n${cmd}${args}\n\nstderr: ${
      commandResult.stderr ?? "empty"
    }`;
    activeLabelFormatted.value = cmd ?? unformattedActiveLabel;
  }
};

const toggleActiveLabel = async () => {
  showAltLabel = !showAltLabel;
  unformattedActiveLabel =
    (showAltLabel ? props.label_alt : props.label) ?? defaultLabel;
  updateActiveLabel();
};

const onCallbackExec = async (exec_options: CallbackTypeExecOptions) => {
  const command = exec_options.cmd;
  const args = tryFormatArgsEval(exec_options?.args ?? [], commandResultData);
  await invoke("process_custom_command", { command, args, timeout: 1000 });
  Log.info(`UnknownWidget: ${command} ${args}`);
};

 */

<span class="widget" [id]="$any(props).kind" [ngClass]="props?.class">{{
  activeLabelFormatted
}}</span>

// src/components/widgets/custom.widget.vue
<!-- eslint-disable @typescript-eslint/no-non-null-assertion -->
<script setup lang="ts">
import { invoke } from "@tauri-apps/api/tauri";
import { ref, onMounted } from "vue";
import { CallbackEvent } from "~/bindings/widget/base/CallbackEvent";
import { CallbackType } from "~/bindings/widget/base/CallbackType";
import { CallbackTypeExec } from "~/bindings/widget/base/CallbackTypeExec";
import { CustomCommandResponse } from "~/bindings/widget/custom/CustomCommandResponse";
import type { CustomWidgetProps } from "~/bindings/widget/custom/CustomWidgetProps";

const props = defineProps<CustomWidgetProps>();

// eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars
let data: any;
let showAltLabel = false;
let activeLabel: string;
let commandResult: CustomCommandResponse;

const defaultLabel = "CustomWidget";
const activeLabelError = ref<string | null>(null);
const activeLabelFormatted = ref<string>(
  props.label_alt ?? props.label ?? defaultLabel
);

onMounted(async () => {
  activeLabel = props.label ?? defaultLabel;

  if (props.command) {
    await executeCommand();

    if (props.command.interval ?? 0 > 0) {
      setInterval(executeCommand, props.command.interval!);
    }
  }
});

const executeCommand = async () => {
  commandResult = await invoke("process_custom_command", {
    command: props.command?.cmd,
    args: props.command?.args ?? [],
    timeout: Math.floor((props.command?.interval ?? 1000) / 2),
  });

  updateActiveLabel();
};

const updateActiveLabel = () => {
  if (commandResult.stdout) {
    try {
      data = JSON.parse(commandResult.stdout);
    } catch {
      data = commandResult.stdout.replace(/(\r\n|\n|\r)/gm, "");
    }
    try {
      const fmt = eval("`" + activeLabel.replace(/`/g, "\\`") + "`");
      activeLabelFormatted.value = fmt;
      activeLabelError.value = null;
    } catch (error) {
      activeLabelFormatted.value = "Error";
      activeLabelError.value = `Error formatting label:\n\n${
        (error as Error).message
      }`;
    }
  } else {
    const cmd = props.command?.cmd;
    const args = ` ${(props.command?.args ?? []).join(" ")}`;
    const status = commandResult.status ?? 1;

    if (commandResult.stderr) {
      activeLabelError.value = `Command: "${cmd}${args}" exited with code: ${status}\n\n${commandResult.stderr}`;
    } else {
      activeLabelError.value = `Unknown Error. Check log for details.`;
    }

    activeLabelFormatted.value = cmd ?? "error";
  }
};

const swapActiveLabel = () => {
  showAltLabel = !showAltLabel;
  activeLabel = (showAltLabel ? props.label_alt : props.label) ?? defaultLabel;
  updateActiveLabel();
};

const processCallback = async (callbackEvent: CallbackEvent) => {
  if (props.callbacks) {
    const callbackType: CallbackType | null = props.callbacks[callbackEvent];

    if (typeof callbackType === "string") {
      switch (callbackType) {
        case "toggle":
          swapActiveLabel();
          break;
        case "update":
          if (props.command) {
            await executeCommand();
          }
          break;
      }
    } else {
      if (callbackType?.exec) {
        await processExecCallback(callbackType as CallbackTypeExec);
      }
    }
  }
};

const processExecCallback = async (callback: CallbackTypeExec) => {
  const command = callback?.exec?.cmd;
  const args = callback.exec.args ?? [];

  // format any args that might be template literals
  tryFormatArgs(args);

  await invoke("process_custom_command", { command, args, timeout: 1000 });
};

const tryFormatArgs = (args: string[]) => {
  args.map((arg) => {
    try {
      return eval("`" + arg.replace(/`/g, "\\`") + "`");
    } catch (error) {
      return arg;
    }
  });
};

const mouseoutUntoggle = () => {
  if (props.callbacks?.on_hover === "toggle") {
    swapActiveLabel();
  }
};
</script>

<template>
  <span
    :data-toggle="!!activeLabelError"
    :title="activeLabelError ?? ''"
    :class="['widget', props.class, { error: !!activeLabelError }]"
    @click.left="processCallback('on_left')"
    @click.middle="processCallback('on_middle')"
    @click.right="processCallback('on_right')"
    @mouseover="processCallback('on_hover')"
    @mouseout="mouseoutUntoggle()"
  >
    {{ activeLabelFormatted }}
  </span>
</template>
